version: "3.6"

services:
  database:
    image: postgres:14.5
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
    ports:
    - "65432:5432"
    volumes:
    - "./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql"
  flyway:
    build:
      context: .
      dockerfile: db/Dockerfile
